// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmjfonqpxiscyparrmxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtamZvbnFweGlzY3lwYXJybXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyODI2NTIsImV4cCI6MjA3Mjg1ODY1Mn0.1e6hhyjCqeb2J8X06ewTPvsjaUeJD8Bxg7SFkrw0eOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});